version: '3.4'

services:
  everybus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  db:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P4ssW0rd!
    ports:
      - "1433:1433"
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu 