version: "3.4"
services:
    everybus:
        image: ${DOCKER_REGISTRY-}everybus
        build:
            context: .
            dockerfile: EveryBus/Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: mysql
        ports:
            - "1234:3306"
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1
            MYSQL_DATABASE: buses
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbuserpassword
        volumes:
            - bus-data:/var/lib/mysql
        restart: always

volumes:
    bus-data: