name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker-compose build
      
    - uses: elgohr/Publish-Docker-Github-Action@master
    - name: Publish to Docker Hub
      with:
        name: chaining/everybus
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - uses: digitalocean/action-doctl@master
    - name: Download lastest Docker image on Droplet
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: compute ssh ubuntu-s-1vcpu-1gb-lon1-01
