name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build container image (Git SHA)
      run: docker build -t chaining/everybus:$(echo $GITHUB_SHA | head -c7) .
    - name: Build container image (Latest)
      run: docker build -t chaining/everybus:latest .

    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Push image to Docker Hub ($(echo $GITHUB_SHA | head -c7))
      run: docker push chaining/everybus:$(echo $GITHUB_SHA | head -c7)
    - name: Push image to Docker Hub (Latest)
      run: docker push chaining/everybus:latest

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        debug: true
        script: docker pull chaining/everybus:latest
